#!/bin/bash

set -e

mkdir -p /data/elasticsearch
cd /usr/share/elasticsearch
su -c "/usr/share/elasticsearch/bin/elasticsearch --default.path.logs=/var/log/elasticsearch --default.path.data=/data/elasticsearch --default.path.conf=/etc/elasticsearch" elasticsearch
