#cloud.kubernetes.service: ${SERVICE}
#cloud.kubernetes.namespace: ${KUBERNETES_NAMESPACE}
#discovery.type: kubernetes

path.data: '/data/elasticsearch'
script.engine.groovy.inline.aggs: on
http.cors.enabled: true

metrics.riemann.every: 60
metrics.riemann.host: ${RIEMANN_HOST:-localhost}
metrics.riemann.tags: "elasticsearch"
